; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = spotpear-esp32s3-max35

[env:spotpear-esp32s3-max35]
platform = espressif32@^6.6.0
board = esp32-s3-devkitc-1
framework = arduino
extra_scripts = pre:scripts/platformio_lvgl_filter.py
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.flash_mode = qio
board_build.flash_size = 16MB
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 16777216
board_build.partitions = default_16MB.csv
upload_port = /dev/cu.usbmodem14101
monitor_speed = 115200
monitor_filters = esp32_exception_decoder
build_flags = 
	-D BOARD_HAS_PSRAM
	-D ARDUINO_USB_MODE=1
	-D ARDUINO_USB_CDC_ON_BOOT=1
	
	-D LV_CONF_INCLUDE_SIMPLE
	-D LV_USE_DRAW_SW_ASM=0
	-I include
	
	-D USER_SETUP_LOADED=1
	-D USE_HSPI_PORT=1
	-D ST7796_DRIVER=1
	-D TFT_WIDTH=320
	-D TFT_HEIGHT=480
	-D TFT_MISO=-1
	-D TFT_MOSI=48
	-D TFT_SCLK=46
	-D TFT_CS=5
	-D TFT_DC=47
	-D TFT_RST=-1
	-D TFT_BL=42
    -D TFT_BACKLIGHT_ON=LOW
	-D SPI_FREQUENCY=40000000
	-D SPI_READ_FREQUENCY=20000000
	-D LOAD_GLCD=1
	-D LOAD_FONT2=1
	-D LOAD_FONT4=1
	-D LOAD_FONT6=1
	-D LOAD_FONT7=1
	-D LOAD_FONT8=1
	-D LOAD_GFXFF=1
	-D SMOOTH_FONT=1
	
	-D CORE_DEBUG_LEVEL=3
	-O2
lib_deps = 
	bodmer/TFT_eSPI@^2.5.43
	tamctec/TAMC_GT911@^1.0.2
	Wire
	SPI
	FS
	SPIFFS
	lvgl/lvgl@9.2.2
	tzapu/WiFiManager@2.0.17
